### ISSUE TITLE
How do we Integrate with Typescript-react? It doesn't contain any @types export?

### ISSUE THREAD

**Issue by Prabhat2373** [esdete2/react-mirt#1]

**Comment by esdete2** [comment]
I'm not sure I understand you correctly. There are several exported interfaces in the npm package. Could you provide more informations?

**Comment by godson-pius** [comment]
@Prabhat2373 Did you find a way around it, I seem to be having same issue

<img width="1274" alt="Error" src="https://github.com/esdete2/react-mirt/assets/40927597/3abd1131-355d-4b6c-b97b-39e3d9b88346">

**Comment by esdete2** [comment]
I'll take a look at the problem!
