### ISSUE TITLE
Audio Playback Not Working on Mobile Devices

### ISSUE THREAD

**Issue by BaileyMcKelway** [esdete2/react-mirt#4]
I'm encountering an issue with the react-mirt library where audio playback is not functioning correctly on mobile devices. The play button appears disabled, and the audio does not play even after a direct user interaction. The happens on all browsers.

#### Steps to Reproduce:
- Use the Mirt component with an audio file on a mobile device.
- Attempt to play the audio using the play button.

**Comment by esdete2** [comment]
Thank you for your report! It looks like some browsers (at least Safari on iOS) are no longer firing the `canplaythrough` event. I just tested it with the `loadedmetadata` event and it works fine. I'll create a new release. Please let me know if this fixes the bug.

**Comment by esdete2** [comment]
The playback now works on my device, but unfortunately the audio playback position does not change when I move the marker.. I'm on it

**Comment by esdete2** [comment]
Ok, it's fixed. Please try version 1.3.5 and let me know if it works for you as well! :)

**Comment by BaileyMcKelway** [comment]
Fantastic! Thank you so much! I will report back on Monday.

**Comment by BaileyMcKelway** [comment]
Everything is working well! I'll close the issue. Thanks again!
